# Generated by Django 4.0.4 on 2022-05-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
